# Generated by Django 4.1.4 on 2022-12-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('social', models.CharField(max_length=300)),
                ('last_dination', models.DateField()),
                ('bio', models.TextField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
