# Generated by Django 4.1.4 on 2022-12-13 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blod_group',
            field=models.CharField(default=datetime.datetime(2022, 12, 13, 5, 40, 4, 854881, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=datetime.datetime(2022, 12, 13, 5, 40, 13, 790218, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
