# Generated by Django 4.1.4 on 2022-12-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_userprofile_blod_group_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
    ]
