# Generated by Django 4.1.4 on 2022-12-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_donorlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=300)),
            ],
        ),
    ]
